name: tools
description: 我常用的工具
version: 1.0.0

environment:
    sdk: '>=2.12.0 <3.0.0'

dependencies:
    mongo_dart: ^0.9.1
    shelf: ^1.2.0
    shelf_router: ^1.1.1

dev_dependencies:
    lints: ^2.0.0
    test: ^1.16.0
